import { Dimensions, Platform } from 'react-native';
import { Colors } from './colors';
export const Constants = {
    CORNER_RADIUS: 4,
    BORDER_RADIUS: 56,
    BORDER_WIDTH: 1,
    MARGIN: 4,
    MARGIN8: 8,
    MARGIN12: 12,
    MARGIN16: 16,
    MARGIN24: 24,
    MARGIN36: 36,
    MARGIN48: 48,
    PADDING: 4,
    PADDING8: 8,
    PADDING12: 12,
    PADDING16: 16,
    PADDING24: 24,
    PADDING36: 36,
    AVATAR_SIZE: 36,
    AVATAR_CHILD_COMMENT: 24,
    AVATAR_COMMENT: 32,
    SMALL_CIRCLE: 60,
    BIG_CIRCLE: 70,
    MAX_SIZE_UPLOAD: 25,
    DIVIDE_HEIGHT_SMALL: 1,
    QUICK_ANSWER_HEIGHT: 40,
    DIVIDE_HEIGHT_MEDIUM: 2,
    DIVIDE_HEIGHT_LARGE: 4,
    WIDTH_TIMER_COUNTDOWN: 30,
    MARGIN_UPLOAD_WRITING: 50,
    MARGIN_UPLOAD_WRITING_SUBMIT: 70,
    PICKER_HEIGHT: 40,
    PAGE_SIZE: 20, //Page size for load list
    BUTTON_RADIUS: 20, //Radius corner
    STR_SPACE: ' ',
    STR_BETWEEN: ' - ',
    STR_BRACKET_LEFT: ' (',
    STR_BRACKET_RIGHT: ') ',
    STR_TOKEN: ', ',
    TOP_AVATAR_PROFILE: 90,
    LEFT_AVATAR_PROFILE: 14,
    SHADOW: 4,
    SHADOW_BLUR: 16,
    ACTIVE_OPACITY: 0.7,
    SHADOW_OPACITY: 0.25,
    ELEVATION: 4,
    SHADOW_OFFSET_WIDTH: 0,
    SHADOW_OFFSET_HEIGHT: 4,
    SHADOW_OPACITY_BUTTON: 0.5,
    SHADOW_OPACITY_EDIT_TEXT: 0.08,
    MARGIN_XX_LARGE: 32,
    PADDING_XX_LARGE: 32,
    STATUS_BAR_HEIGHT: 18,
    MARGIN_TITLE_ONE_BTN: 28,
    PADDING_TITLE_ONE_BTN: 28,
    MARGIN8_TITLE_ONE_BTN: 56,
    PADDING8_TITLE_ONE_BTN: 56,
    HEIGHT_CARD_MEMBER: 70,
    AVATAR_WIDTH_HEIGHT: 68,
    HEIGHT_BUTTON: 52,
    WIDTH_BANK: 80,
    HEIGHT_BANK: 50,
    HEADER_HEIGHT: 56,
    NAV_HEIGHT: 50,
    OPACITY_50: 0.5,
    HEIGHT_HEADER_OFFSET_REFRESH: Platform.OS === 'ios' ? 0 : 44,
    MAX_WIDTH: Dimensions.get('screen').width,
    MAX_HEIGHT: Dimensions.get('screen').height,
    LATITUDE_DEFAULT: 10.8030269,
    LONGITUDE_DEFAULT: 106.7220181,
    ANDROID_RIPPLE: {
        color: Colors.COLOR_RIPPLE,
        borderless: false,
    },
    TOOLBAR_HEIGHT: Platform.OS === 'ios' ? 64 : 56,
    BANNER_WIDTH: Dimensions.get('screen').width - 32,
    BANNER_BRAND_HEIGHT: Dimensions.get('screen').width * (1 / 3),
    BANNER_HEIGHT: Dimensions.get('screen').width * (9 / 21),
};
